services:
  - type: cron
    name: bot_ev_plus
    schedule: "*/10 * * * *"
    runtime: python
    plan: free
    repo: https://github.com/Chiquillo77/Valor_EV
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: "7738392758:AAFsMfvVcA1xingWTYmwdBjkR2DO6ozP8Ek"
      - key: CHAT_ID
        value: "7943883784"
      - key: MIN_PROB
        value: "0.70"
      - key: MIN_ODDS
        value: "1.60"
      - key: MIN_EV
        value: "0.01"
