services:
  - type: worker
    name: bot-ev-plus-worker
    runtime: python
    repo: https://github.com/Chiquillo77/Valor_EV.git
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: 7738392758:AAFsMfvVcA1xingWTYmwdBjkR2DO6ozP8Ek
      - key: CHAT_ID
        value: "7943883784"
